# Generated by Django 5.2.7 on 2025-11-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_lat', models.FloatField()),
                ('origem_lng', models.FloatField()),
                ('destino_lat', models.FloatField()),
                ('destino_lng', models.FloatField()),
                ('geojson', models.JSONField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
