# Generated by Django 5.2.7 on 2025-12-04 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0002_predio_delete_rota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('route', 'Rota'), ('search', 'Pesquisa')], default='route', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_rota', to='rota.predio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_rota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
