# Generated by Django 5.2.7 on 2025-11-01 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Predio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("coordenadas", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Prédios",
            },
        ),
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("sala de aula", "Sala de aula"),
                            ("banheiro", "Banheiro"),
                            ("restaurante", "Restaurante"),
                            ("biblioteca", "Biblioteca"),
                            ("departamento", "Departamento"),
                            ("laboratório", "Laboratório"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField()),
                ("andar", models.CharField(max_length=50)),
                ("localizacao_detalhada", models.TextField()),
                ("coordenadas", models.JSONField(blank=True, null=True)),
                ("informacoes_extras", models.JSONField(blank=True, null=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "predio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locais",
                        to="mapa.predio",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Locais",
                "ordering": ["predio", "andar", "nome"],
            },
        ),
    ]
