# Generated by Django 5.2.7 on 2025-11-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="local",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("sala de aula", "Sala de aula"),
                    ("banheiro", "Banheiro"),
                    ("restaurante", "Restaurante"),
                    ("biblioteca", "Biblioteca"),
                    ("administrativo", "Administrativo"),
                    ("laboratório", "Laboratório"),
                    ("outro", "Outro"),
                ],
                max_length=20,
            ),
        ),
    ]
