# Generated by Django 5.2.7 on 2025-11-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_alter_local_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='localizacao_detalhada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
