# Generated by Django 5.2.7 on 2025-11-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0004_favoritolocal_favoritopredio'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='search_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='local',
            name='sugerido_padrao',
            field=models.BooleanField(default=False),
        ),
    ]
